### ISSUE TITLE
discord server 401认证失败

### ISSUE THREAD

**Issue by Caco355** [trueai-org/midjourney-proxy#10]
配置文件：
默认设置，只填写了discordserverid，discordchannelid和discordusertoken
日志报错：
[10:46:24 INF] 2024/7/26 10:46:24  [ Warning] Gateway:  Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
[10:46:24 INF] 2024/7/26 10:46:24  [    Info] Gateway: Disconnecting
[10:46:24 INF] 2024/7/26 10:46:24  [    Info] Gateway: Disconnected

**Comment by trueai-org** [comment]
你好，必须配置机器人 token，才可以。

机器人 Token（必须配置）
本项目利用 Discord 机器人 Token 连接 wss，可以获取错误信息和完整功能，确保消息的高可用性等问题。

1. 创建应用
https://discord.com/developers/applications

2. 设置应用权限（确保拥有读取内容权限，参考截图）
[Bot] 设置 -> 全部开启

3. 添加应用到频道服务器（参考截图）

client_id 可以在应用详情页找到，为 APPLICATION ID

https://discord.com/oauth2/authorize?client_id=xxx&permissions=8&scope=bot

4. 复制或重置 Bot Token 到配置文件
设置应用权限（确保拥有读取内容权限，参考截图）

设置应用权限

添加应用到频道服务器（参考截图）

添加应用到频道服务器

**Comment by trueai-org** [comment]
项目启动后，可以通过web后台配置。

![image](https://github.com/user-attachments/assets/68a08b08-e97c-453a-875d-aaddb45cf606)

**Comment by trueai-org** [comment]
你好，是否还存在问题，没有问题的话，我就关闭了哦
