### ISSUE TITLE
[Bug] 账号可以正常提交 但是数据同步时报错

### ISSUE THREAD

**Issue by hibikico** [trueai-org/midjourney-proxy#62]
https://github.com/trueai-org/midjourney-proxy/issues/61

这个issue的问题刚通过重启docker容器解决

在重启容器后，垫图可以正常上传，任务可正常提交，重启之前的账号也还在，能正常连接，但是点击同步按钮尝试同步数据时会报错Bad Request

![image](https://github.com/user-attachments/assets/8ba92845-275a-49e7-958c-83f177535320)

docker镜像版本： `v5.12.0`

（可能的）复现流程：

1. 创建docker容器
2. 调整系统设置，配置好MongoDB并添加账号
3. 账号连接成功
4. 重启docker容器确保配置生效
5. 点击账号的同步按钮
6. 报错BadRequest

**Comment by hibikico** [comment]
相关配置截图与系统日志：
![image](https://github.com/user-attachments/assets/93a780a4-91ea-46b4-ba21-784cae128db2)
![image](https://github.com/user-attachments/assets/f5e4858e-d017-4e86-b311-bd81d070447a)
![image](https://github.com/user-attachments/assets/bf7ad372-69f7-4f54-962e-f2f278d17e51)
![image](https://github.com/user-attachments/assets/44318954-2120-49ed-b4c1-74a2d0c79f6c)
![image](https://github.com/user-attachments/assets/257de554-e306-4630-90ea-4b8061c5cd88)

```
2024-11-11 09:45:54.596 +08:00 [INF] 当前可用账号数 [1] - 1302775819596468375
2024-11-11 09:45:54.597 +08:00 [INF] 例行检查完成
2024-11-11 09:45:55.438 +08:00 [ERR] Http 请求执行失败 {
  "type": 2,
  "guild_id": "1302775819147415694",
  "channel_id": "1302775819596468375",
  "session_id": "09c56382377e1ee478f75d808b4933b8",
  "nonce": "1855789017328877568",
  "application_id": "1022952195194359889",
  "data": {
    "version": "1248805223925940264",
    "id": "1023054140634579025",
    "name": "settings",
    "type": 1,
    "options": [],
    "application_command": {
      "id": "1023054140634579025",
      "type": 1,
      "application_id": "1022952195194359889",
      "version": "1248805223925940264",
      "name": "settings",
      "description": "View and adjust your personal settings.",
      "dm_permission": true,
      "contexts": [
        0,
        1,
        2
      ],
      "integration_types": [
        0,
        1
      ],
      "global_popularity_rank": 3,
      "options": [],
      "description_localized": "View and adjust your personal settings.",
      "name_localized": "settings"
    },
    "attachments": []
  },
  "analytics_location": "slash_ui"
}, "BadRequest", {"Headers":[{"Key":"Content-Type","Value":["application/json"],"$type":"KeyValuePair`2"},{"Key":"Content-Length","Value":["49"],"$type":"KeyValuePair`2"}],"$type":"HttpConnectionResponseContent"}
2024-11-11 09:45:55.440 +08:00 [WRN] 逻辑错误 BadRequest: {
  "type": 2,
  "guild_id": "1302775819147415694",
  "channel_id": "1302775819596468375",
  "session_id": "09c56382377e1ee478f75d808b4933b8",
  "nonce": "1855789017328877568",
  "application_id": "1022952195194359889",
  "data": {
    "version": "1248805223925940264",
    "id": "1023054140634579025",
    "name": "settings",
    "type": 1,
    "options": [],
    "application_command": {
      "id": "1023054140634579025",
      "type": 1,
      "application_id": "1022952195194359889",
      "version": "1248805223925940264",
      "name": "settings",
      "description": "View and adjust your personal settings.",
      "dm_permission": true,
      "contexts": [
        0,
        1,
        2
      ],
      "integration_types": [
        0,
        1
      ],
      "global_popularity_rank": 3,
      "options": [],
      "description_localized": "View and adjust your personal settings.",
      "name_localized": "settings"
    },
    "attachments": []
  },
  "analytics_location": "slash_ui
Midjourney.Infrastructure.LogicException: BadRequest: {
  "type": 2,
  "guild_id": "1302775819147415694",
  "channel_id": "1302775819596468375",
  "session_id": "09c56382377e1ee478f75d808b4933b8",
  "nonce": "1855789017328877568",
  "application_id": "1022952195194359889",
  "data": {
    "version": "1248805223925940264",
    "id": "1023054140634579025",
    "name": "settings",
    "type": 1,
    "options": [],
    "application_command": {
      "id": "1023054140634579025",
      "type": 1,
      "application_id": "1022952195194359889",
      "version": "1248805223925940264",
      "name": "settings",
      "description": "View and adjust your personal settings.",
      "dm_permission": true,
      "contexts": [
        0,
        1,
        2
      ],
      "integration_types": [
        0,
        1
      ],
      "global_popularity_rank": 3,
      "options": [],
      "description_localized": "View and adjust your personal settings.",
      "name_localized": "settings"
    },
    "attachments": []
  },
  "analytics_location": "slash_ui
   at Midjourney.Infrastructure.Services.TaskService.InfoSetting(String id) in /src/src/Midjourney.Infrastructure/Services/TaskService.cs:line 1104
   at Midjourney.API.Controllers.AdminController.SyncAccount(String id) in /src/src/Midjourney.API/Controllers/AdminController.cs:line 492
   at lambda_method189716(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-11-11 09:45:55.463 +08:00 [INF] 用户已发送 HEARTBEAT 消息 1302775819596468375
```

**Comment by liqiujiong** [comment]
之前遇到过，是不是你两个机器人信息没加全？
